module.exports = {
    SAVE_USER: "/saveUser",
    DELETE_USER: "/deleteUser/:id",
    VALIDATE_USERID: "/validatedUserId",
    GET_USERS: "/getAllUsers",
    GET_USER_BY_ID: "/getUserById/:id",
    UPDATE_USER_STATUS: "/updateUserStatus",
    AUTH_LOGIN: "/login",
    GET_MASTERS: "/getAllMaster",
    ADD_NEW_ASSET: "/addAsset",
    DELETE_ASSET_FROM_LIST: "/deleteAsset/:id",
    UPDATE_ASSET: "/updateAsset",
    UPDATE_ASSET_STATUS: "/updateAssetStatus",
    ASSIGN_ASSET: "/assignAssetStatus",
    REMOVE_USER_ASSET: "/removeUserAsset/:userId/:assetId",
    GET_ALL_ASSETS: "/getAllAssets",
    ASSET_UPDATE_USER: "/updateAssignedAsset",
    AVAILABLE_ASSET_FOR_USER: "/availableAssets/:userId",
    GET_ADMIN_USER: "/getUserForAdmin/:loginId",
    UPDATE_USER_IN_SYSTEM: "/updateUserInSystem",
    ADD_USER_IN_SYSTEM: "/addUserInSystem",
    GET_USER_SYSTEM: "/getUserInSystem",
    DELETE_USER_FROM_SYSTEM: "/deleteUserFromSystem/:id",
    CHANGE_PASSWORD: "/updatePassword",
    REPORT_DOWNLOAD: "/downloadReport",
    ADD_RESOURCE: "/addResource",
    REMOVE_RESOURCE: "/removeResource"
}